### ISSUE TITLE
add visually hidden

### ISSUE THREAD

**Issue by phucbm** [viivue/atomic-css#24]
We need this to leverage the support to a11y.

```css
/* Visually hidden */
.visually-hidden {
    position:absolute;overflow:hidden;clip:rect(0 0 0 0);
    width:1px;height:1px;margin:-1px;padding:0; border:0;
}
```

Read more in [this article](https://www.joshwcomeau.com/snippets/react-components/visually-hidden/).
