### ISSUE TITLE
specific transition properties

### ISSUE THREAD

**Issue by phucbm** [viivue/atomic-css#25]
## Why
We need to specify the transition properties instead of using `transition:all` in order to bypass the "avoid non-composited animations" issue from Lighthouse.

![Screenshot 2023-05-23 at 15 30 17](https://github.com/viivue/atomic-css/assets/14942380/bba901fe-811a-4033-889b-23a3c341c34a)

## How

```css
.t-transform {transition-property: transform;}
.t-transform-opacity {transition-property: transform, opacity;}
.t-transform-opacity-color {transition-property: transform, opacity, color;}
.t-transform-color {transition-property: transform, color;}
.t-opacity-color {transition-property: opacity, color;}
.t-opacity {transition-property: opacity;}
.t-color {transition-property: color;}
```

## Ref
- https://developer.chrome.com/docs/lighthouse/performance/non-composited-animations
- https://github.com/viivue/atomic-css/blob/main/scss/transitions.scss
