### ISSUE TITLE
feat: container sizes

### ISSUE THREAD

**Issue by phucbm** [viivue/atomic-css#30]
Create options to add multiple container sizes, and provide related CSS variables and classes.

Usage demo:
```css
/* variables */
:root {
    /* Container */
    --bb-container:1076px;
    --bb-container-large:1196px;
    --bb-container-xl:1290px;
}

/* Container */
.container, .container-large, .container-xl {
    position:relative; width:100%; max-width:calc(var(--bb-container) + var(--bb-gap-container) * 2);
    margin-right:auto; margin-left:auto;
    padding-right:var(--bb-gap-container); padding-left:var(--bb-gap-container);
}
.container {max-width:calc(var(--bb-container) + var(--bb-gap-container) * 2);}
.container-large {max-width:calc(var(--bb-container-large) + var(--bb-gap-container) * 2);}
.container-xl {max-width:calc(var(--bb-container-xl) + var(--bb-gap-container) * 2);}
```
