### ISSUE TITLE
Add top, right, bottom, left auto

### ISSUE THREAD

**Issue by phucbm** [viivue/atomic-css#9]
```css
.t-auto { top:auto; }
/* same for other props */
```

https://github.com/viivue/atomic-css/blob/main/css/positioning.css
